var scenarios = [
  "Worst Places To Do Acid",
  "Movies That Are Just Okay",
  "Pets That Nobody Should Ever Have",
  "Weird-Looking Animals",
  "Legal Things That Are So Addictive They Should Be Banned",
  "Things to Not Be Caught Doing in Your Parents' House",
  "Things You've Googled That Nobody Else Has Ever Googled",
  "Things You Will Probably Never Do with a Priest",
  "Religions That Are Probably Right",
  "Places to Film a Western",
  "Toilets in New York City",
  "Gross Noises That Aren't Farts",
  "Vacation Spots for Crazy People",
  "Places to Unwind with a Glass of Wine",
  "Planets That Aren't in Our Solar System",
  "Places to Start a Cult",
  "Best Places to Start a Revolution",
  "Worst Places to Have a Threesome",
  "Best Tools for the Aspiring Artist",
  "Best Places to Meet Insane People",
  "Worst Places to Propose",
  "Best Places to Do the Macarena",
  "Worst Places to Start a Business",
  "Best Things to Cure that Nasty Cold",
  "Weirdest Things to Bring on a Plane",
  "Most Useful Things in the Kitchen",
  "Weirdest Things in Your Refrigerator",
  "Best Comedic Objects",
  "Places to Ride a Mechanical Bull",
  "Animals You Almost Never See",
  "Scariest Animals",
  "Best Places to Eat",
  "Best Places to Go for a Run",
  "Worst Places to Raise a Family",
  "Best Things to Use as Weapons",
  "Worst Things to Say to Your Dentist",
  "Worst Things to Hear From Your Doctor",
  "Worst Things to Hear From a Priest",
  "Best Shapes",
  "Most Terrifying Animals",
  "Worst Things to Hear From Your Boss",
  "Weirdest Places to Walk Your Dog",
  "Things to Find in a Boat",
  "Things to Find Under Your Bed",
  "Places to Hide from Gremlins",
  "Things You Just Know Are True Despite Lacking Evidence",
  "Things You Use in the Morning",
  "Things You Use in the Evening",
  "Things You Bring with You When You Travel",
  "Things You Can't Live Without",
  "Things That Grind Your Gears",
  "Best Places for Bizarre, Off-putting People",
  "Worst Things to Find in Your Mailbox",
  "Worst Things to See in Your Email Inbox",
  "Worst Things to Hear from a Psychic",
  "Best Places to Watch a Magic Show",
  "Best Vacation Spots in the USA",
  "Weirdest Sounding Netflix Documentaries"
];
